ports:
  - port: 8080  # keycloak
    onOpen: open-browser
    visibility: public
  - port: 16686 # jaeger
    onOpen: open-browser
    visibility: public
  - port: 9464  # prometheus
    onOpen: open-browser
    visibility: public
  - port: 9990  # wildfly management
    onOpen: open-browser
    visibility: public

tasks:    
  - name:   docker-compose
    init:
      docker-compose -f .gitpod/docker-compose-gitpod.yml up -d --build && docker logs -f keycloak
