version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686   
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile-keycloak-with-opentelemetry
    ports:
      - 8080:8080 # Keycloak
      #- 9464:9464 # Prometheus OTEL metrics exporter
      - 9990:9990 # WildFly Management /metrics
    environment:
      JAVA_OPTS_APPEND: "-javaagent:/tmp/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: keycloak
      OTEL_TRACES_EXPORTER: jaeger
      xOTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      URI_METRICS_ENABLED: "true"
      KEYCLOAK_STATISTICS: all
    depends_on:
      - jaeger
    command:
      - "-bmanagement=0.0.0.0"
