FROM jboss/keycloak:latest

# see https://github.com/aerogear/keycloak-metrics-spi/releases
ARG KEYCLOAK_METRICS_SPI_RELEASE=2.5.1
# https://search.maven.org/artifact/io.opentelemetry/opentelemetry-sdk-extension-aws/1.7.0/jar

RUN \
  curl -L https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent-all.jar \
  -o /tmp/opentelemetry-javaagent-all.jar && \
  curl -L https://github.com/aerogear/keycloak-metrics-spi/releases/download/${KEYCLOAK_METRICS_SPI_RELEASE}/keycloak-metrics-spi-${KEYCLOAK_METRICS_SPI_RELEASE}.jar \
  -o /opt/jboss/keycloak/standalone/deployments/keycloak-metrics-spi.jar